### ISSUE TITLE
I can't download Citra!

### ISSUE THREAD

**Issue by AGhostWithGames** [citra-emu/citra-bleeding-edge#7]
Here's the info:

11312> 2016-10-22 17:07:41> Unhandled exception: System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

2016-11-11 20:28:45> Unhandled exception: System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

2016-11-11 20:35:09> Unhandled exception: System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

2016-11-11 20:37:13> Unhandled exception: System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

2016-11-11 20:52:03> Unhandled exception: System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)

=== Pre-bind state information ===
LOG: DisplayName = PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase = file:///C:/Users/ecahmad/AppData/Local/SquirrelTemp/
LOG: Initial PrivatePath = NULL
Calling assembly : Update.exe, Version=1.4.3.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: No application configuration file found.
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
LOG: Attempting download of new URL file:///C:/Users/ecahmad/AppData/Local/SquirrelTemp/PresentationFramework.DLL.
LOG: Attempting download of new URL file:///C:/Users/ecahmad/AppData/Local/SquirrelTemp/PresentationFramework/PresentationFramework.DLL.
LOG: Attempting download of new URL file:///C:/Users/ecahmad/AppData/Local/SquirrelTemp/PresentationFramework.EXE.
LOG: Attempting download of new URL file:///C:/Users/ecahmad/AppData/Local/SquirrelTemp/PresentationFramework/PresentationFramework.EXE.

2016-11-11 20:52:41> Unhandled exception: System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)

=== Pre-bind state information ===
LOG: DisplayName = PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase = file:///C:/Users/ecahmad/AppData/Local/SquirrelTemp/
LOG: Initial PrivatePath = NULL
Calling assembly : Update.exe, Version=1.4.3.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: No application configuration file found.
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
LOG: Attempting download of new URL file:///C:/Users/ecahmad/AppData/Local/SquirrelTemp/PresentationFramework.DLL.
LOG: Attempting download of new URL file:///C:/Users/ecahmad/AppData/Local/SquirrelTemp/PresentationFramework/PresentationFramework.DLL.
LOG: Attempting download of new URL file:///C:/Users/ecahmad/AppData/Local/SquirrelTemp/PresentationFramework.EXE.
LOG: Attempting download of new URL file:///C:/Users/ecahmad/AppData/Local/SquirrelTemp/PresentationFramework/PresentationFramework.EXE.

2016-11-11 20:53:03> Unhandled exception: System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)

=== Pre-bind state information ===
LOG: DisplayName = PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase = file:///C:/Users/ecahmad/AppData/Local/SquirrelTemp/
LOG: Initial PrivatePath = NULL
Calling assembly : Update.exe, Version=1.4.3.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: No application configuration file found.
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
LOG: Attempting download of new URL file:///C:/Users/ecahmad/AppData/Local/SquirrelTemp/PresentationFramework.DLL.
LOG: Attempting download of new URL file:///C:/Users/ecahmad/AppData/Local/SquirrelTemp/PresentationFramework/PresentationFramework.DLL.
LOG: Attempting download of new URL file:///C:/Users/ecahmad/AppData/Local/SquirrelTemp/PresentationFramework.EXE.
LOG: Attempting download of new URL file:///C:/Users/ecahmad/AppData/Local/SquirrelTemp/PresentationFramework/PresentationFramework.EXE.

2016-11-11 20:53:35> Unhandled exception: System.IO.FileNotFoundException: Could not load file or assembly 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)

=== Pre-bind state information ===
LOG: DisplayName = PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase = file:///C:/Users/ecahmad/AppData/Local/SquirrelTemp/
LOG: Initial PrivatePath = NULL
Calling assembly : Update.exe, Version=1.4.3.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: No application configuration file found.
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
LOG: Attempting download of new URL file:///C:/Users/ecahmad/AppData/Local/SquirrelTemp/PresentationFramework.DLL.
LOG: Attempting download of new URL file:///C:/Users/ecahmad/AppData/Local/SquirrelTemp/PresentationFramework/PresentationFramework.DLL.
LOG: Attempting download of new URL file:///C:/Users/ecahmad/AppData/Local/SquirrelTemp/PresentationFramework.EXE.
LOG: Attempting download of new URL file:///C:/Users/ecahmad/AppData/Local/SquirrelTemp/PresentationFramework/PresentationFramework.EXE.

If you help me,thanks.

**Comment by jroweboy** [comment]
That looks like an issue with squirrel not citra. Try to reinstall .net framework 4.0 found here https://www.microsoft.com/en-us/download/details.aspx?id=17851

**Comment by JayFoxRox** [comment]
This is a bug tracker for developers of Citra.

Please use the [Citra Forum for questions and support](https://discuss.citra-emu.org/) instead.
Note that there is limited support for bleeding-edge.

---

We'll fix the installer / docs once we know whats wrong
Closed as invalid
